// makeHttpRequest("GET", 'https://dummyjson.com/users')
//     .then((userData) => makeHttpRequest("GET", `https://dummyjson.com/users/${userData.users[0].id}/posts`))
//     .then((postData) => makeHttpRequest("GET", `https://dummyjson.com/posts/${postData.posts[0].id}/comments`))
//     .then((cmntData) => makeHttpRequest("GET", `http://dummyjson.com/users/${cmntData.comments[0].user.id}`))
//     .then((userCmnt)=> console.log(userCmnt))
//     .catch((err) => console.log(err))


fetch('https://dummyjson.com/users')
    .then(res => res.json())
    .then(userData => fetch(`https://dummyjson.com/users/${userData.users[0].id}/posts`))
    .then(res => res.json())
    .then(postData => fetch(`https://dummyjson.com/posts/${postData.posts[0].id}/comments`))
    .then(res => res.json())
    .then(cmntData => fetch(`http://dummyjson.com/users/${cmntData.comments[0].user.id}`))
    .then(res => res.json())
    // .then(console.log)
    .then(cmntUser => console.log(cmntUser))
    .catch(err => console.log(err))